kind = "api"
previewPath = "/api" # TODO - should be excluded from preview in the first place
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api"]

[services.development]
run = "cd ../.. && uv run --locked uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[services.production]

[services.production.build]
args = ["uv", "sync", "--project", "../..", "--locked", "--no-dev"]

[services.production.run]
args = ["sh", "-c", "cd ../.. && uv run --no-sync uvicorn app.main:app --host 0.0.0.0 --port 8080"]

[services.production.run.env]
PORT = "8080"

[services.production.health.startup]
path = "/api/healthz"
