"""create billing domain schema

Revision ID: dd3399d4697c
Revises:
Create Date: 2026-08-23 09:01:32.302515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd3399d4697c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('monthly_price_cents', sa.BigInteger(), nullable=False),
    sa.Column('included_api_calls', sa.BigInteger(), nullable=False),
    sa.Column('included_ai_tokens', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('included_ai_tokens >= 0', name='ck_plans_included_ai_tokens_nonnegative'),
    sa.CheckConstraint('included_api_calls >= 0', name='ck_plans_included_api_calls_nonnegative'),
    sa.CheckConstraint('monthly_price_cents >= 0', name='ck_plans_monthly_price_cents_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_plans_code')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_webhook_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_processed_webhook_events_tenant_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_event_id', name='uq_processed_webhook_events_stripe_event_id')
    )
    op.create_index('ix_processed_webhook_events_tenant_id', 'processed_webhook_events', ['tenant_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name='fk_subscriptions_plan_id'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_subscriptions_tenant_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id', name='uq_subscriptions_stripe_subscription_id')
    )
    op.create_index('ix_subscriptions_plan_id', 'subscriptions', ['plan_id'], unique=False)
    op.create_index('ix_subscriptions_tenant_id', 'subscriptions', ['tenant_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('usage_type', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("usage_type IN ('api_call', 'ai_token')", name='ck_usage_events_usage_type'),
    sa.CheckConstraint('quantity > 0', name='ck_usage_events_quantity_positive'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_usage_events_tenant_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_usage_events_tenant_idempotency_key')
    )
    op.create_index('ix_usage_events_tenant_occurred_at', 'usage_events', ['tenant_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_events_tenant_occurred_at', table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index('ix_subscriptions_tenant_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_plan_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_processed_webhook_events_tenant_id', table_name='processed_webhook_events')
    op.drop_table('processed_webhook_events')
    op.drop_table('tenants')
    op.drop_table('plans')
    # ### end Alembic commands ###
